### PR TITLE
Update to 1.90g

### PR DESCRIPTION
**Pull request by Discomanco**
This is a full rebuild of E2ES, scrapping the old profile, built from E2E 1.90f from the ground up again by applying the SkyBlock specific changes, just like the first one back in the day.
Version numbers should now follow E2E, and skyblock specific hotfixes will get its own numbering, e.g. 1.90g-a.

This will most likely not be compatible with old E2ES worlds. It might work, but it is very untested.

(also there's no dev branch here, so it goes to master)

### CODE REVIEW

**Comment by NielsPilgaard** [comment]
Good work :D I have a few questions:

- Did you remove the mods that do not make sense in skyblock? (and their configs/scripts)
- Did you update the main menu back to the skyblock version?
- I see the gem / terrestrial artifact textures are gone, is that intentional?

**Comment by Discomanco** [comment]
A couple changes were made.

* I did remove all the same mods from the original skyblock and their configs and scripts like TF, Pretty Beaches, Horse Tweaks etc. The one exception here is Biomes O' Plenty. While it's not exactly needed for skyblock, it is what all our AR planets rely on, so I've kept it in.
* I did not update the main menu, I forgot about that
* With BoP no longer removed, the custom gems are no longer needed

The changes from old E2ES made are:
* Updated to 1.90, obviously
* It's now all Plains, no other biomes. (I did decide to keep Natures Compass before making this change sooo, maybe chop?, maybe keep for space?)
* Squid now spawn in all water below y40
* Bats only spawn between y10-y20 (or somewhere around there)

**Comment by NielsPilgaard** [comment]
Apart from the main menu, perfect. Good call on BoP imo.

**Review by NielsPilgaard — CHANGES_REQUESTED** [review]
I'd like the main menu restored, other than that I approve :)

**Comment by Discomanco** [comment]
There we go :P
Baldurs Gate 3 kinda stole my life the past 2 weeks

**Review by NielsPilgaard — APPROVED** [review]

**Comment by NielsPilgaard** [comment]
That was super helpful, thanks!

**Pull request merged**
